### ISSUE TITLE
The influence on the scheduler in infinite loop threads.

### ISSUE THREAD

**Issue by carlosdelfino** [micro-os-plus/micro-os-plus.github.io-source#13]
Translating the subtitle "Infinite loop threads" in [threads.md](https://github.com/micro-os-plus/micro-os-plus.github.io-source/blob/master/pages/user-manual/threads.md) file, the influence of this type of scheduler threads or the thread consuming more time that the scheduler determines each to use the CPU, I came up with the following question.

According to the text,

> The infinite loop must call a µOS++ service that will cause the thread to pass control back to the scheduler, for example a service to wait for an event to occur, or sleep for a certain duration. It is important that each thread will pass control back to the scheduler, otherwise the thread would be a true busy wait loop and will simply hog the CPU for the time quanta it is allowed to run. This concept of **suspending waiting threads** is key to an efficient CPU use in any RTOS.

Then, if we use an infinite loop without calling to any Service UOS ++, the thread will completely consume the CPU, which seems strange, since the scheduler not being suspended and stopping the charge timer for latch it the scheduler being active, this should not happen. Since from time to time (typically 1 ms) there will be a context switch, giving the opportunity to the other threads being executed according to the priority of each.

This is a UOS ++ characteristic or the text was not clear on this issue, being a misunderstanding.

**Comment by ilg-ul** [comment]
you missed a detail:

> will simply hog the CPU for **the time quanta** it is allowed to run

in other words the scheduler will give opportunity to other high priority threads to run, but when no other high priority threads are ready, the infinite loop thread will get the CPU.

all priority based schedulers do this, since the schedulers have no way of differentiating a busy loop wait from a long computation.

if, by mistake, the thread is the highest priority thread, no other thread will be able to run.

**Comment by carlosdelfino** [comment]
Got It.

**Comment by ilg-ul** [comment]
do you have suggestions to improve the text?

**Comment by carlosdelfino** [comment]
I have reactivated my MAC station, and so finish this translation step will start making practical tests with the UOS.

If you have documented the tests you've done, so I can repeat them, using various scenarios, including the use of QEMU and some ARM, I have two here one Arduino DUE (Sam3) and one Atmel xPlaned with a SAM4 and other RaspeberryPI if possible test Cortex-A also want to test.

**Comment by ilg-ul** [comment]
> SAM4

this one should be more than enough to run µOS++.

> use of QEMU

the DUE Arduino support in QEMU for not ready.

> test Cortex-A

if you want to contribute a Cortex-A port, that's fine, but for now I don't have one.

**Comment by carlosdelfino** [comment]
Eu reescrevi o comentário (o tradutor não é meu amigo) :)

**Comment by carlosdelfino** [comment]
I thought you had done some testing with it, for example using QEMU to emulate a Cortex-A.

but in the future when Domir the Cortex-M as it is my plan, I will definitely want to make new bare-metal experiments with Cortex-A.

**Comment by ilg-ul** [comment]
> using QEMU to emulate a Cortex-A.

GNU ARM Eclipse QEMU supports Cortex-M only. for Cortex-A, I guess the mainstream QEMU must be used, but I remember they had some problems with semihosting, I don't know if it is functional now.

> definitely want to make new bare-metal experiments with Cortex-A

yes, that would be interesting, and I think it shouldn't be that difficult. as inspiration for the context switching code, the FreeRTOS port for Cortex-A should be ok.

**Comment by ilg-ul** [comment]
any more comments on the scheduler related to infinite loops, or we can close this ticket?

**Comment by carlosdelfino** [comment]
thanks.
