### ISSUE TITLE
Thread priorities with direct numbering.

### ISSUE THREAD

**Issue by carlosdelfino** [micro-os-plus/micro-os-plus.github.io-source#14]
Tha subtitle "Thread priorities" in file "[threads.md](https://github.com/micro-os-plus/micro-os-plus.github.io-source/blob/master/pages/user-manual/threads.md)" the text suggests that the numeration of priorities is direct, ie the higher the priority is the number.

In all RTOS I seen, that this identification is reversed, ie the lower the number the higher the priority,

I just wanted to confirm this statement, since it is more common to numerical inversion of priorities, ie the lower the number the higher the priority ..

**Comment by ilg-ul** [comment]
I confirm, for CMSIS++, higher values mean higher priorities.

**Comment by ilg-ul** [comment]
should we explain this more than it is explained now?

**Comment by carlosdelfino** [comment]
:)
it´s ok.
thanks.
