### ISSUE TITLE
Gem for optimize Jekyll on Windows

### ISSUE THREAD

**Issue by carlosdelfino** [micro-os-plus/micro-os-plus.github.io-source#17]
I have added WDM GEM parametrized for install only on windows in Gemfile, please see commit: 49042b1baeeaea44c150c14e31f7ec8afeb9b7c5

**Comment by ilg-ul** [comment]
simply adding this gem is enough? no need to explicitly tell jekyll about it?

**Comment by carlosdelfino** [comment]
Only on command line: http://jekyll-windows.juthilo.com/4-wdm-gem/

**Comment by ilg-ul** [comment]
this sounds a Windows specific issue, on macOS `jekyll serve` does not require any gem.

**Comment by carlosdelfino** [comment]
Yes, is only for how use windows, and is installed automatically if in windows.
In Brasil Mac is good choice but not a comum choice.

**Comment by carlosdelfino** [comment]
in line:

```
gem 'wdm', '>= 0.1.0' if Gem.win_platform?
```

the parameter`if Gem.win_platform?` make the bundler install only if on Windows.

**Comment by ilg-ul** [comment]
I added it.

as a separate notice, the `Gemfile.lock` mechanism is a joke, you cannot use mine, I cannot use yours, so it makes little sense.

**Comment by carlosdelfino** [comment]
It seems a Cache, but really the first sight it seems useless, but looking deeper, helps identify the versions used.

In a certain way I think it should be kept a reference version, that is, which is ideal to have installed to the proper functioning of Gems.

**Comment by carlosdelfino** [comment]
more about Gemfile.lock, is good or not?
http://bundler.io/v1.5/man/bundle-install.1.html

> If a Gemfile.lock does exist, and you have not updated your Gemfile(5), bundler will fetch all remote sources, but use the dependencies specified in the Gemfile.lock instead of resolving dependencies.
> 
> If a Gemfile.lock does exist, and you have updated your Gemfile(5), bundler will use the dependencies in the Gemfile.lock for all gems that you did not update, but will re-resolve the dependencies of gems that you did update. You can find more information about this update process below under CONSERVATIVE UPDATING.

**Comment by ilg-ul** [comment]
> is good or not?

I don't mind keeping it for reference in the repo, but I doubt it'll be of any use for you.

**Comment by carlosdelfino** [comment]
In a certain way has been useful so far, since with it whenever I had problems like we had with the language plugin, I was sure he was using the same gems you the same version. And no time needed to question whether it was a matter of version.

This is the only validates it. Keep the synchronized version.

Without it we would have to lock versions directly in Gemfile.

but of course this is not so important, I think just a minor good practice.

**Comment by ilg-ul** [comment]
ok, we'll keep it. from time to time, not very often, I'll do a bundle update, and if everything goes well, I'll update the lock in the repo.

if you have any problems with the new versions, suggest which versions to lock, and we'll revert.

**Comment by carlosdelfino** [comment]
ok, 

for now, all is ok.
