### ISSUE TITLE
Taking the first steps with the uOS.

### ISSUE THREAD

**Issue by carlosdelfino** [micro-os-plus/micro-os-plus.github.io-source#18]
Let's assume that I am a young student and want to get started with an RTOS and choose the uOS as my studies reference.

I (this young student) I find the User Manual (http://micro-os-plus.github.io/user-manual/) and start to read it and decide to start using uOS finally.

What would be the road-map to success with my study?

Carlos Delfino, I, I know I need to install GCC, Eclipse, GNU-Eclipse-Plugin, but the next steps? from perspective of this young student with little knowledge and little or nothing experience in Cortex-M and even less in the GCC and uOS, what steps should be taken?

It would be interesting to have a type page "Road-Map for the use uOS" or "First Step with uOS," to shorten the way for beginners.

**Comment by ilg-ul** [comment]
right, that would be helpful for beginners.

since you definitely have more teaching experience, what would be an outline for such a document?

should this be a separate manual, or should we enhance the "Getting started" page of the "User's manual"?

as for sample code, I currently have the two demo projects. did you take a look at them?

the project structure is not yet final, the code might be split into different xPacks, but as a first version it should be ok.

**Comment by carlosdelfino** [comment]
After "Basic Concepts is a good place to create a new subcapter, "Prepare your environment for use with uOS".

However, I think is good have a link on "Get started" to jump direct for "Prepare your environment.." for the anxious beginner possa pular a teoria.

E claro deixar claro na seção "Prepare your environment..." a importante de ler todo o manual para se compreender todos os conceitos envolvidos.

I do not take this responsibility now, because not mastered English for writing, but also still feel with little knowledge to assume such reporting responsibilities with reference to all the tools.

But with the Commitment, I'm having soon be able to take to the Portuguese language.

About samples I want, can be at github? as a post?

my SAM4xPlaned of atmel was damaged in my change of city, 2300km traveled by bus and the box with my equipment crashed, I have to see if I recover it, would now begin to experiment with the UOS today. With it I can debug, already with Arduino DUE no debugging ..
![img00292](https://cloud.githubusercontent.com/assets/369056/18022111/9504898a-6bc2-11e6-995d-e912ac059f37.jpg)

**Comment by ilg-ul** [comment]
> demo projects:

https://github.com/micro-os-plus/eclipse-demo-projects

you can run the F4DISCO on QEMU.

**Comment by carlosdelfino** [comment]
Ok, on my workspace.
Thanks.

**Comment by ilg-ul** [comment]
> my SAM4xPlaned of atmel was damaged ... begin to experiment with the UOS today.

I strongly recommend to start the first tests with the emulated F4DISCOVERY, and the blinky demo.

**Comment by carlosdelfino** [comment]
I'm having trouble with Eclipse CDT Neon, it's not finding the GCC tools and MAKE already hit the path in many ways, and he always complain about not find the make and part of the GCC tools.

Visibly is a BUG Eclipse, or may be the GNU ARM Eclipse, I tested all shell commands and all work.

Look:
![include f4-disco](https://cloud.githubusercontent.com/assets/369056/18029563/a585481c-6c71-11e6-9f8d-ab8d20e52b08.gif)

**Comment by ilg-ul** [comment]
as I said, **none of those paths should be there**. really. you need to configure them in Eclipse, at their proper places.

I guess I repeat this mantra some tens of times, in all pages.

**Comment by ilg-ul** [comment]
another point: you should avoid using the same workspace with different versions of Eclipse, you risk damaging them irreparably.

**Comment by carlosdelfino** [comment]
Really I made this mistake have two eclipse Eclipse JEE + CDT and the Eclipse CDT pure, perhaps this is the cause of this problem.

About mantra, I confess I did not notice this message before, despite the rich documentation, it seems to me sometimes overloaded with information, maybe it made some people do not read everything, and jump important steps, there is a saying: "Less is More".

I will remove the workspace and create it from scratch again.

**Comment by ilg-ul** [comment]
> some people do not read everything

bad mistake.

following the steps "by the book" results in success. otherwise... big gamble. many times... misery.

> "Less is More".

does not apply to install steps.

**Comment by ilg-ul** [comment]
btw, the video is not shown properly with Safari on Mac.

**Comment by carlosdelfino** [comment]
When I say "less is more" is because in some tutorials there are two or three tool options, an example: using or not using Mentor Graphics Sourcery, if it is not a good best option or quote, to consolidate on the GCC ARM none EABI available on Launchpad.

But it certainly was a mistake to me to have not read the section that spoke not to set the path, although it seems to me that the problem lies in the fact that I have made a small change in the path manually, without considering the fact that Eclipse le dais windows registry information. Everything was working on a version and stopped in the other.

For me it is important to test in different scenarios, so I insist do the same windows having a MAC, and when I have time I test the LInux with changes in various parameters to see results, so I can transfer the acquired knowledge and support to others for example students. Nothing is lost time, everything becomes knowledge, but I understand their position and respect.

I am running in a totally new environment, and now everything seems ok.

The video is a GIF file, do not know why does not work in Safari. Chrome and Firefox is ok.

**Comment by ilg-ul** [comment]
> an example or not to use Sourcery Mentor Grafics, if it is not a good best option or quote, to consolidate on the GCC ARM none EABI available on Launchpad.

I'm not sure I get this, but initially CodeSourcery was the preferred toolchain; after ARM decided to support development for arm-none-eabi-gcc, it became, together with the Linaro toolchains, the preferred ones.

**Comment by carlosdelfino** [comment]
Now all work fine, but Debug with GDB not work like this old issues:

https://sourceforge.net/p/gnuarmeclipse/support-requests/42/
https://sourceforge.net/p/gnuarmeclipse/bugs/104/

I'm trying to find the problem here, as played with QEMU, but did not get to much, and for debugging only used the J-LInk with SAM4SxPlaned and had no problems.

Let me do more testing and review the material, if you can not we open issue in the repository of samples.

**Comment by carlosdelfino** [comment]
all fine.
thanks.
